program: train_hpo.py
project: hyperparameter-optimization-mmd-lr-scheduler
method: bayes

metric:
  goal: minimize
  name: loss
parameters:
  hidden_layers:
    values: [1, 2, 3, 4, 5]
  hidden_dim:
    values: [8, 16, 32, 64]
  learning_rate:
    min: 0.00001
    max: 0.01
  batch_size:
    values: [8, 16, 64, 512] 
  epochs:
    values: [10,50,100,200]
  bw:
    values: [0.0001, 0.001, 0.01, 0.1, 1.0]
  lambda_bce:
    values: [0.0, 0.01]
  optimizer:
    values: ['adam', 'sgd']